{
 "title": "CRUD Dashboard",
 "tags": [ "asgn-09-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Read Operation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tutorial_read_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Create Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tutorial_create_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Update Operation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tutorial_update_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Delete Operation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tutorial_delete_total", "legendFormat": "__auto" }
   ]
  }
 ]
}