{
 "title": "Ubuntu VM Monitoring",
 "tags": [ "asgn-09-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "VM Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"jenkins-node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"10.4.85.47:9100\"} \n/ node_memory_MemTotal_bytes{instance=\"10.4.85.47:9100\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Root Disc Space",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"10.4.85.47:9100\", mountpoint=\"/\", fstype!=\"tmpfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"jenkins-node\", mode=\"idle\"}[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Total Memory (I set it 6GB during configuration)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"10.4.85.47:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}